name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Fastlane install 1
        run: gem install bundle

      - name: Fastlane install 2
        run: bundle install

      - name: Update Fastlane
        run:  bundle update fastlane

      - name: Chmod gradlew
        run:  chmod +x gradlew

      - name: Build debug APK with Fastlane
        run:  bundle exec fastlane build_debug


      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug